export type Wilaya = {
  code: string;
  nameLatin: string;
  nameArabic: string;
};

export const WILAYAS: readonly Wilaya[] = [
  { code: '01', nameLatin: 'Adrar', nameArabic: 'أدرار' },
  { code: '02', nameLatin: 'Chlef', nameArabic: 'الشلف' },
  { code: '03', nameLatin: 'Laghouat', nameArabic: 'الأغواط' },
  { code: '04', nameLatin: 'Oum El Bouaghi', nameArabic: 'أم البواقي' },
  { code: '05', nameLatin: 'Batna', nameArabic: 'باتنة' },
  { code: '06', nameLatin: 'Béjaïa', nameArabic: 'بجاية' },
  { code: '07', nameLatin: 'Biskra', nameArabic: 'بسكرة' },
  { code: '08', nameLatin: 'Béchar', nameArabic: 'بشار' },
  { code: '09', nameLatin: 'Blida', nameArabic: 'البليدة' },
  { code: '10', nameLatin: 'Bouira', nameArabic: 'البويرة' },
  { code: '11', nameLatin: 'Tamanrasset', nameArabic: 'تمنراست' },
  { code: '12', nameLatin: 'Tébessa', nameArabic: 'تبسة' },
  { code: '13', nameLatin: 'Tlemcen', nameArabic: 'تلمسان' },
  { code: '14', nameLatin: 'Tiaret', nameArabic: 'تيارت' },
  { code: '15', nameLatin: 'Tizi Ouzou', nameArabic: 'تيزي وزو' },
  { code: '16', nameLatin: 'Alger', nameArabic: 'الجزائر' },
  { code: '17', nameLatin: 'Djelfa', nameArabic: 'الجلفة' },
  { code: '18', nameLatin: 'Jijel', nameArabic: 'جيجل' },
  { code: '19', nameLatin: 'Sétif', nameArabic: 'سطيف' },
  { code: '20', nameLatin: 'Saïda', nameArabic: 'سعيدة' },
  { code: '21', nameLatin: 'Skikda', nameArabic: 'سكيكدة' },
  { code: '22', nameLatin: 'Sidi Bel Abbès', nameArabic: 'سيدي بلعباس' },
  { code: '23', nameLatin: 'Annaba', nameArabic: 'عنابة' },
  { code: '24', nameLatin: 'Guelma', nameArabic: 'قالمة' },
  { code: '25', nameLatin: 'Constantine', nameArabic: 'قسنطينة' },
  { code: '26', nameLatin: 'Médéa', nameArabic: 'المدية' },
  { code: '27', nameLatin: 'Mostaganem', nameArabic: 'مستغانم' },
  { code: '28', nameLatin: "M'Sila", nameArabic: 'المسيلة' },
  { code: '29', nameLatin: 'Mascara', nameArabic: 'معسكر' },
  { code: '30', nameLatin: 'Ouargla', nameArabic: 'ورقلة' },
  { code: '31', nameLatin: 'Oran', nameArabic: 'وهران' },
  { code: '32', nameLatin: 'El Bayadh', nameArabic: 'البيض' },
  { code: '33', nameLatin: 'Illizi', nameArabic: 'إليزي' },
  { code: '34', nameLatin: 'Bordj Bou Arréridj', nameArabic: 'برج بوعريريج' },
  { code: '35', nameLatin: 'Boumerdès', nameArabic: 'بومرداس' },
  { code: '36', nameLatin: 'El Tarf', nameArabic: 'الطارف' },
  { code: '37', nameLatin: 'Tindouf', nameArabic: 'تندوف' },
  { code: '38', nameLatin: 'Tissemsilt', nameArabic: 'تيسمسيلت' },
  { code: '39', nameLatin: 'El Oued', nameArabic: 'الوادي' },
  { code: '40', nameLatin: 'Khenchela', nameArabic: 'خنشلة' },
  { code: '41', nameLatin: 'Souk Ahras', nameArabic: 'سوق أهراس' },
  { code: '42', nameLatin: 'Tipaza', nameArabic: 'تيبازة' },
  { code: '43', nameLatin: 'Mila', nameArabic: 'ميلة' },
  { code: '44', nameLatin: 'Aïn Defla', nameArabic: 'عين الدفلى' },
  { code: '45', nameLatin: 'Naâma', nameArabic: 'النعامة' },
  { code: '46', nameLatin: 'Aïn Témouchent', nameArabic: 'عين تموشنت' },
  { code: '47', nameLatin: 'Ghardaïa', nameArabic: 'غرداية' },
  { code: '48', nameLatin: 'Relizane', nameArabic: 'غليزان' },
  { code: '49', nameLatin: 'Timimoun', nameArabic: 'تيميمون' },
  { code: '50', nameLatin: 'Bordj Badji Mokhtar', nameArabic: 'برج باجي مختار' },
  { code: '51', nameLatin: 'Ouled Djellal', nameArabic: 'أولاد جلال' },
  { code: '52', nameLatin: 'Béni Abbès', nameArabic: 'بني عباس' },
  { code: '53', nameLatin: 'In Salah', nameArabic: 'عين صالح' },
  { code: '54', nameLatin: 'In Guezzam', nameArabic: 'عين قزام' },
  { code: '55', nameLatin: 'Touggourt', nameArabic: 'تقرت' },
  { code: '56', nameLatin: 'Djanet', nameArabic: 'جانت' },
  { code: '57', nameLatin: "El M'Ghair", nameArabic: 'المغير' },
  { code: '58', nameLatin: 'El Meniaa', nameArabic: 'المنيعة' },
] as const;
